export const texts = {
    appTitle: 'Movies App',
    login: 'Giriş Yap',
    email: 'E-posta',
    password: 'Şifre',
    loginButton: 'Giriş',
    conditions: 'Conditions of Use',
    privacy: 'Privacy & Policy',
    pressRoom: 'Press Room',
    moviesByOctet: '© 2023 Movies by Octet',
    searchPlaceholder: 'What do you want to watch? ',
    subHeaderTitle: 'Movies',
    favorites: 'Favoriler',
    sort: 'Sırala',
    filter: 'Filtrele',
    filmName: 'Film Adı',
    releaseDate: 'Vizyon Tarihi',
    ImdbScore: 'Imdb Puanı',
}
